### ISSUE TITLE
Support logging configuration

### ISSUE THREAD

**Issue by WetHippie** [inkblot/puppet-bind#109]
Bind has an extensive logging configuration that needs to go in named.conf. This gets wiped out due to puppet managing the entire file.  Makes it very difficult to setup say syslog management for this file. Please add support for the logging clause in the main bind class.

**Comment by makeacode** [comment]
I actually updated some parts of this module about a month ago but never submitted a pull request with the changes.  I'll try to get that done tonight and submit the PR.

**Comment by makeacode** [comment]
Just submitted my PR #110.  Feel free to check it out.

**Comment by WetHippie** [comment]
Looks pretty good just reading the patches. I haven't tried to use it directly. My current hack is to just specify the logging file with a File resource and then use a File_line resource to tack on the handler at the end.

**Comment by makeacode** [comment]
I've been using these changes for a month or so and they've worked well for me.

**Comment by inkblot** [comment]
I'll try to give this feature request some attention in the next week.

**Comment by makeacode** [comment]
somehow i managed to close the PR I submitted...still learning git apparently.  I've submitted a new PR #114 with the same changes (hopefully)

**Comment by inkblot** [comment]
@WetHippie Please have a look at #115 and let me know if it meets your needs.

@makeacode the changes in #114 implement a style of puppet configuration that I don't like. Also, I have seen that exact code before, probably from the place you found it.

**Comment by WetHippie** [comment]
Might as well close now that we have a config in the main release
