### ISSUE TITLE
init zone

### ISSUE THREAD

**Issue by rgarrigue** [inkblot/puppet-bind#118]
Hi

I'm creating a zone with your module, and the initial SOA record is localhost. root.localhost. Tracking down the code I see it's from db.empty, a file.

Why isn't it a template with the correct SOA ? Or is it meant to be updated asap ? Might be a possibility, since I am otherwise stuck with NOTAUTH error trying to get a local key to word.

**Comment by inkblot** [comment]
Bind does not allow or deny updates based on the content of the SOA record. Your dynamic updates are being denied for some other reason. As for updating the SOA record, you can do this with nsupdate, but I don't recommend automating it since the record contains the zone serial.

**Comment by rgarrigue** [comment]
Granted for the NOTAUTH issue, I don't remember the exact reason since we've been thinkering Bind & puppet for a week, but it's gone.

Well, I've been thinking about this a bit, I still don't feel confortable with this localhost thing. I understood you saying this is not blocking. But it feels unfinished to me. I'ld expect the module to either 
- give me a ready to go brand new zone with the zone name I provide, serial 1, nameserver Ip provided. 
- or resume an existing zone if a file is given

Again maybe this is my newbie understanding. I guess you can close this issue, since now I see how to use this.
