### ISSUE TITLE
This module basically requires puppet 4

### ISSUE THREAD

**Issue by lingfish** [inkblot/puppet-bind#119]
Hi, in attempting to use this module in my Puppet 3 environment, a chain of dependencies basically meant I would have to upgrade my master etc to 4.

Requiring puppetlabs-concat >=2.0.0 then (from memory) set off a chain reaction, needing something like a newer stdlib, newer postgresql, newer puppetdb.

**Comment by inkblot** [comment]
Puppet 3 is out of support. I'll update the `.travis.yml` file.
