### ISSUE TITLE
Puppet 3 & 4 compatibility

### ISSUE THREAD

**Issue by cedef** [inkblot/puppet-bind#122]
Working on issue #40, I've cloned the repo and I see that the master branch is still using ripienaar-module_data making it Puppet3 compatible only.
A good practice I've seen at voxpupuli Puppet repos would be to create a puppet3 branch and to backport features from master (which would be puppet4-only).

Before working on it I would like to:
- drop branch puppet-4 as it seems to be deprecated (last commit 6 months ago)
- create a branch puppet3 from branch master
- drop ripienaar-module_data usage on master

Do you agree with that change ?

**Comment by inkblot** [comment]
I think you're missing about six months of commits. The `puppet-4` branch was merge in October and the module no longer supports puppet 3.

**Comment by cedef** [comment]
The ripienaar-module_data being still part of `.fixtures.yml` I've misunderstood the puppet4-only orientation of the module.
