### ISSUE TITLE
puppetlabs/concat

### ISSUE THREAD

**Issue by jean-gui** [inkblot/puppet-bind#134]
Any plans to make this module compatible with current version of concat? Thanks!

**Comment by acurus-puppetmaster** [comment]
This is now causing conflicts on my puppet master when librarian tries to resolve dependencies.

Will need to look for another module if this one isn't brought up to date.

**Comment by inkblot** [comment]
Just tested it. Seems ok.

**Comment by inkblot** [comment]
It is done.
