### ISSUE TITLE
This provider (Resource_record) is not idempotent with TXT records.

### ISSUE THREAD

**Issue by pankrat-bel** [inkblot/puppet-bind#37]
Hello, inkblot!
Module Version 4.0.4 
Sun May 17 10:59:50 +0300 2015 /Stage[main]/Bind/Resource_record[dc1netview@m.example.ru@mngt01@TXT]/ensure (notice): created
Sun May 17 10:59:52 +0300 2015 Puppet (notice): Finished catalog run in 23.40 seconds
Sun May 17 11:29:53 +0300 2015 /Stage[main]/Bind/Resource_record[dc1netview@m.example.ru@mngt01@TXT]/data (notice): data changed ['"IBM" "Management" "Port"'] to 'IBM Management Port'
Sun May 17 11:29:57 +0300 2015 Puppet (notice): Finished catalog run in 25.84 seconds
Sun May 17 11:59:50 +0300 2015 /Stage[main]/Bind/Resource_record[dc1netview@m.example.ru@mngt01@TXT]/ensure (notice): created
Sun May 17 11:59:54 +0300 2015 Puppet (notice): Finished catalog run in 23.95 seconds
Sun May 17 12:29:49 +0300 2015 /Stage[main]/Bind/Resource_record[dc1netview@m.example.ru@mngt01@TXT]/data (notice): data changed ['"IBM" "Management" "Port"'] to 'IBM Management Port'
Sun May 17 12:29:52 +0300 2015 Puppet (notice): Finished catalog run in 23.02 seconds

**Comment by pankrat-bel** [comment]
I'm sorry, forgot to specify 
; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.30.rc1.el6_6.2

**Comment by inkblot** [comment]
Can you also show me the resource declaration from your manifest?

**Comment by pankrat-bel** [comment]
Yes, I can.
Here is a fragment from the test manifest:

 $zone_record_instances = hiera('zone_record_instances', [])

 $ttl=72800
 $key=keys($zone_record_instances)
 $title=$key[0]
 $title_array = split($title,'@')
 $view = $title_array[0]
 $zone = $title_array[1]
 $rname = $title_array[2]
 $type = $title_array[3]

 $record = "${rname}.${zone}"
 $data=$zone_record_instances[$title]
 resource_record { $title:
    ensure  => present,
	  record => $record,       # fqdn
	  zone => $zone,
	  data => $data,
	  type => $type,
	  ttl => $ttl,
 }

Here is a fragment from hiera:

zone_record_instances:
    "dc1netview@m.example.ru@mngt01@TXT":
      data: 'IBM Management Port'

**Comment by pankrat-bel** [comment]
http://www.zytrax.com/books/dns/ch8/txt.html

**Comment by inkblot** [comment]
Ah, I understand this issue. I had worked around it in my own manifests, but I will fix it now.

**Comment by inkblot** [comment]
I have release version 4.1.1 of this module to the Puppet Forge which includes a fix for this issue.

**Comment by inkblot** [comment]
There is a small typo in the change that I made to fix this issue which may result in a "can't convert Symbol to String" error in some cases. Are you experiencing this error?
