### ISSUE TITLE
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class bind

### ISSUE THREAD

**Issue by mmernik** [inkblot/puppet-bind#43]
Hi,

I have problem my spec:
OS: CentOS 7 
Bind: 9.10.2
Puppet: 3.7.5
Module installed from: forge.puppetlabs.com 

puppet module install inkblot-bind 
puppet module upgrade --force inkblot-bind --environment=production

Manifest configuration : 
  class { 'bind':
    confdir    => '/etc/bind',
    cachedir   => '/var/lib/bind',
    forwarders => [
        '8.8.8.8',
        '8.8.4.4',
    ],
    dnssec     => true,
    version    => 'Controlled by Puppet',
  }

Error:
May 28 10:46:07 puppet-master-01 puppet: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class bind at /etc/puppet/environments/production/manifests/<NOD_NAME>.pp on node <NOD_NAME>

Is there any dependency that it needs to be resolved ?

Thank you.

**Comment by inkblot** [comment]
The dependencies are listed in the `metadata.json` file. The `bind` module requires modules `puppetlabs-stdlib`, `puppetlabs-concat` version 1.x, and `ripienaar-module_data`.

**Comment by mmernik** [comment]
Hi,

All modules are installed and version matches:

[root@mb-puppet-master-01 manifests]# puppet module install 
puppetlabs-stdlib
Notice: Preparing to install into 
/etc/puppet/environments/production/modules ...
Notice: Module puppetlabs-stdlib 4.6.0 is already installed.

[root@mb-puppet-master-01 manifests]# puppet module install 
puppetlabs-concat  --version 1
Notice: Preparing to install into 
/etc/puppet/environments/production/modules ...
Notice: Module *puppetlabs-concat 1.2.2* is already installed.

[root@mb-puppet-master-01 manifests]# puppet module install 
ripienaar-module_data
Notice: Preparing to install into 
/etc/puppet/environments/production/modules ...
Notice: Module ripienaar-module_data 0.0.3 is already installed.

But i have the same error:
May 28 15:13:35 DNS-Primary puppet-agent[5734]: Could not retrieve 
catalog from remote server: Error 400 on SERVER: 
Puppet::Parser::AST::Resource failed with error ArgumentError: Could not 
find declared class bind at 
/etc/puppet/environments/production/manifests/dns-primary.pp:19 on node 
dns-primary


Dne 28.5.2015 ob 14:46 je Nate Riffe zapisal(a):

**Comment by inkblot** [comment]
Sorry I haven't come back to this issue in almost two weeks. It's been a busy time. If you have solved this I am interested in knowing what fixed the problem.

I think that this is probably a long shot, but are you certain that the location where the modules are installed is in the puppet master's `modulepath`? This is the only scenario I can think of in which the parser would be unable to find the class.

**Comment by inkblot** [comment]
I intend to close this issue in a few days.
