### ISSUE TITLE
SRV record failing - update failed: NOTZONE

### ISSUE THREAD

**Issue by VAdamec** [inkblot/puppet-bind#46]
Release 4.2.0, setting A/CNAMEs/.. is ok, but SRV failing on this:

Jun 19 11:17:19 localhost puppet-agent[10825]: (/Stage[main]/Profile::example/Resource_record[sip.tls.example.com]/ensure) change from absent to present failed: Execution of '/usr/bin/nsupdate -y hmac-sha256:local-update:XXXXXX== /tmp/dns_rr-nsupdate-20150619-10825-57vcx1-0' returned 2: update failed: NOTZONE

  bind::zone { 'example.com':
      zone_type       => 'master',
      domain          => 'example.com',
      ns_notify       => false,
      dnssec          => false,
      allow_updates   => [ 'key local-update', ],
  }

bind::view { 'all':
    recursion          => true,
    match_destinations => [ 'any', ],
    zones              => [ 'example.com', ]
}

resource_record { 'sip.tls.example.com':
      ensure  => present,
      record  => [ '_sip._tls' ],
      type    => 'SRV',
      data    => [ '10 10 443	sip.example.com.' ],
      ttl     => 3600,
      zone    => 'example.com',
      keyname => 'local-update',
      hmac    => 'hmac-sha256',
      secret  => 'XXXXXX=='
  }

bind-9.8.2-0.30
bind-utils-9.8.2-0.30

Any advice ?

**Comment by inkblot** [comment]
The value of the `record` property should be fully-qualified. Try changing `_sip._tls` to `_sip._tls.example.com`.

**Comment by inkblot** [comment]
Also, that should be a string, not an array of strings.

**Comment by VAdamec** [comment]
Ah, ok record => [ '_sip._tls.example.com' ] is the correct one (I'm used to write full form in bind like this _sipfederationtls._tcp.example.com.	SRV		10 10 443	sip.example.com.) and missing ending dot makes me feel nervous :-)
