### ISSUE TITLE
$::bind::params::nsupdate_package never installed on osfamily RedHat

### ISSUE THREAD

**Issue by aimonb** [inkblot/puppet-bind#50]
Hi, the class bind::updater is never called so fails with no suitable provider error since binaries are missing. if I call it the bind::keydir inside conflicts with the one in init.pp.  Is this in transition atm? How is bind::updater intended to be used?

Thanks!

**Comment by inkblot** [comment]
The `bind` and `bind::updater` classes are mutually exclusive. The use case for `bind::updater` is when a system which is not a nameserver needs to be able to perform dynamic DNS updates remotely, against a nameserver which has been configured to accept them. More specifically, the `bind::updater` class should install everything that is necessary for the `resource_record` resource type to function correctly in the system's catalog.

Can you send the error message you're seeing? I don't have any RedHat systems to try this on (the parameterization for $osfamily == RedHat was submitted by another user).

**Comment by aimonb** [comment]
The only error is 'Could not find a suitable provider for resource_record'. This is because it cannot find the 'dig' binary. 'bind-utils' is required but not installed. I'll submit a PR for the fix later today.

**Comment by inkblot** [comment]
Great, thanks!

**Comment by aimonb** [comment]
PR is in! Took a day to get through internal CI and gating.

**Comment by aimonb** [comment]
Resolved in latest release.
