### ISSUE TITLE
Allow setting option managed-keys-directory

### ISSUE THREAD

**Issue by fonk** [inkblot/puppet-bind#54]
In RHEL7/CentOS7 the default for managed-keys-directory is /var/named with permissions set to 750 for root.named. This leads to messages like

> Sep 07 10:56:07 vm-frank2e named[15279]: 89c168d61b4f57625d526c99a6b7bc716b2d02a52f61e793ef4259584bdd7f1a.mkeys.jnl: create: permission denied
Sep 07 10:56:07 vm-frank2e named[15279]: managed-keys-zone/10-private: sync_keyzone:dns_journal_open -> unexpected error
Sep 07 10:56:07 vm-frank2e named[15279]: managed-keys-zone/10-private: unable to synchronize managed keys: unexpected error
Sep 07 10:56:07 vm-frank2e named[15279]: ea864fecfa6aa789293a6ac9e5395bb0eadd9b6725a5d746934176098d9aa656.mkeys.jnl: create: permission denied
Sep 07 10:56:07 vm-frank2e named[15279]: managed-keys-zone/99-everyone: sync_keyzone:dns_journal_open -> unexpected error
Sep 07 10:56:07 vm-frank2e named[15279]: managed-keys-zone/99-everyone: unable to synchronize managed keys: unexpected error

This could be prevented if we're able to set managed-keys-directory to /var/named/dynamic

**Comment by inkblot** [comment]
I've made some small changes and pushed a branch called `managed-keys-directory`. Could you please try it and let me know if this fixes the problem?

**Comment by fonk** [comment]
Hi, thanks for the fix! I'll test it, but I will need some time as we're rebuilding out dns infrastructure atm...

**Comment by fonk** [comment]
Hi,

sorry for the delay - unfortunately it does not work yet. IMHO it has sth to do with the scoping:

I added the following line in the init.pp directly below "include ::bind::params":
fail("Top-Scope: ${managed_keys_directroy} - Scoped: ${bind::params::managed_keys_directory}")

and got:
Error 400 on SERVER: Top-Scope:  - Scoped: /var/named/dynamic at /etc/puppet/env/opsdev/modules/bind/manifests/init.pp:16

I don't have enough time to track it further down but hopefully that's helps a litttle bit...

Best regards,
Frank

**Comment by inkblot** [comment]
I have pushed a small change to the `managed_keys_directory` branch, but please note that I have rebased the branch onto `master`.

**Comment by inkblot** [comment]
I am going to merge the `managed_keys_directory` branch as-is and close this issue.

**Comment by inkblot** [comment]
The `managed_keys_directory` branch is included in version 4.4.0 on the puppet forge.
