### ISSUE TITLE
Missing support for glue records

### ISSUE THREAD

**Issue by fonk** [inkblot/puppet-bind#55]
Hi,

something like this does not work with dynamic updates, because the dig query that check's for existence gets an ok in the second case:

```
manifest:
create_resources( 'resource_record', hiera('glue_record', {}))

hiera:
glue_record:
  'glue_sub.example.com':
    'record': '%{fqdn}'
    'zone':   'sub.example.com'
    'type':   'A'
    'data':   '%{ipaddress}'
  'glue_example.com':
    'record': '%{fqdn}'
    'zone':   'example.com'
    'type':   'A'
    'data':   '%{ipaddress}'

**Comment by inkblot** [comment]
Glue records for parent and child zones that are served from the same nameserver are unnecessary. Also, there is no way to query for them to make them work anyway.
