### ISSUE TITLE
Duplicate declaration of bind-utils warning

### ISSUE THREAD

**Issue by claflico** [inkblot/puppet-bind#56]
I already install the bind-utils packages on ALL of my CentOS 7 nodes as part of a list of common packages so that I get nslookup & such. When I try to run this on a DNS server I'm getting a warning about duplicate declaration:

Cannot alias Package[bind-tools] to ["bind-utils"] at /etc/puppet/environments/development/modules/common/bind/manifests/init.pp:32; resource ["Package", "bind-utils"] already declared at /etc/puppet/environments/development/modules/custom/profile/manifests/baselin.pp:14 at /etc/puppet/environments/development/modules/common/bind/manifests/init.pp:32

I still want these common packages on my DNS server so would be nice to have a "If not declared then declare" function added to this piece.

**Comment by inkblot** [comment]
I think that this module should be responsible for installation of BIND software. On servers that are not nameservers, you may wish to use the `bind::updater` class instead of including `bind-utils` in a master package list.

**Comment by claflico** [comment]
Can you elaborate a bit more on this then? I don't see anything in the readme on it and can't quite make out what the manifest is doing.

**Comment by inkblot** [comment]
I've added some documentation in #61 for the `bind::updater` class. This is be included in a release soon.
