### ISSUE TITLE
Ubuntu: Platform is not supported

### ISSUE THREAD

**Issue by netflash** [inkblot/puppet-bind#72]
Hello,
I've just upgrade to 5.0.1 and suffering from this error
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Platform is not supported at /etc/puppet/modules/bind/manifests/defaults.pp:17 on node X
```
module version 5.0.1
puppet version 3.8.4
OS - Ubuntu 14.04
```
facter|grep osfamily
osfamily => Debian
```
Could you please help me to solve this ?

PS In versions 4.4.0, 5.0.0 - another error
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Must pass supported to Class[Bind::Params] at /etc/puppet/modules/bind/manifests/init.pp:15
```
PPS module_data installed

**Comment by inkblot** [comment]
Can you please capture the debug log messages related to the `bind::defaults::supported` hiera key? In master mode, these will appear in the puppet master's logs after setting the `log_level` to `debug` or lower level. In masterless mode, they will appear in the standard output of the `puppet apply` command when you use the `--debug` option.

As far as the difference between 5.0.1 and earlier versions of the module, the `bind::params` class has been replaced with the `bind::defaults` class and they serve mostly the same purpose but I have more carefully categorized parameters as ones that belong in this class versus ones that belong in the `bind` class.

I am using this module on Debian, and so I suspect that the issue you are experiencing is probably related to hiera. I know that Debian is supported and Ubuntu should be as well by the same set of defaults.

**Comment by netflash** [comment]
That's something strange just happened.
I've rebstarted puppet master (foreman) and it works now.
Sorry to bother you.

**Comment by inkblot** [comment]
That's OK. I'm glad it worked out.
