### ISSUE TITLE
implement empty-zones-enable

### ISSUE THREAD

**Issue by fonk** [inkblot/puppet-bind#84]
Hi,

it should be possible to set empty-zones-enable as global option in order to forward ptr-requests to other name servers. For more information: https://kb.isc.org/article/AA-00803/0/Why-are-queries-for-some-PTR-records-no-longer-forwarded-since-upgrading-to-BIND-9.9.0.html

For now, we can use forward-zones to workaround this problem.

Best regards,
Frank

**Comment by anoother** [comment]
We've added this in our fork.

I have just opened a PR to get this merged (along with our other changes)

:)
